server:
  port: 9292

authserver-client:
  baseurl: "http://localhost:3000"  
  
authserver:
  baseurl: http://192.168.91.128:9090
resource:
  server:
    baseurl: http://127.0.0.1:9393
 
app:
  baseurl: http://127.0.0.1:9292
     
spring:
  security:
    oauth2:
      client:
        registration:
          auth-server-client:
            client-id: proapp_auth_server_client
            client-secret: proapp_auth@123
            scope: "openid,APP.all"
        provider:
          auth-server-client:
            issuer-uri: "http://localhost:9090"
  jpa:  
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:mysql://localhost:3306/auth_server_2"
    username: "root"
    password: ""
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jackson:
    serialization:
      write-dates-as-timestamps: false
      
  main:
    allow-bean-definition-overriding: true
  codec:
    max-in-memory-size: 10MB
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
              
logging:
  level:
    org:
      springframework:
        security: trace
        
               
